/**
 * Small, bounded syntax lexers for terminal diff presentation. Highlighting is
 * display-only: generated bytes never pass through or depend on this module.
 */
import { extname } from "node:path";
import { languageForCodeExtension } from "../core/languages.ts";

export type SyntaxStyle =
  | "keyword"
  | "type"
  | "function"
  | "string"
  | "number"
  | "comment"
  | "decorator"
  | "builtin"
  | "property"
  | "tag";

export interface SyntaxSpan {
  start: number;
  end: number;
  style: SyntaxStyle;
}

const KEYWORDS: Readonly<Record<string, ReadonlySet<string>>> = Object.freeze({
  typescript: new Set([
    "as", "async", "await", "break", "case", "catch", "class", "const",
    "continue", "debugger", "declare", "default", "delete", "do", "else",
    "enum", "export", "extends", "finally", "for", "from", "function", "if",
    "implements", "import", "in", "instanceof", "interface", "keyof", "let",
    "namespace", "new", "null", "of", "private", "protected", "public", "readonly",
    "return", "satisfies", "static", "super", "switch", "this", "throw", "try",
    "true", "type", "typeof", "undefined", "using", "var", "void", "while",
    "with", "yield", "false",
  ]),
  javascript: new Set([
    "as", "async", "await", "break", "case", "catch", "class", "const",
    "continue", "debugger", "default", "delete", "do", "else", "export",
    "extends", "finally", "for", "from", "function", "if", "import", "in",
    "instanceof", "let", "new", "null", "of", "return", "static", "super",
    "switch", "this", "throw", "true", "try", "typeof", "undefined", "var",
    "void", "while", "with", "yield", "false",
  ]),
  python: new Set([
    "and", "as", "assert", "async", "await", "break", "case", "class",
    "continue", "def", "del", "elif", "else", "except", "False", "finally",
    "for", "from", "global", "if", "import", "in", "is", "lambda", "match",
    "None", "nonlocal", "not", "or", "pass", "raise", "return", "True", "try",
    "while", "with", "yield",
  ]),
  rust: new Set([
    "as", "async", "await", "break", "const", "continue", "crate", "dyn",
    "else", "enum", "extern", "false", "fn", "for", "if", "impl", "in", "let",
    "loop", "match", "mod", "move", "mut", "pub", "ref", "return", "self",
    "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
    "use", "where", "while", "None", "Some",
  ]),
  go: new Set([
    "break", "case", "chan", "const", "continue", "default", "defer", "else",
    "fallthrough", "for", "func", "go", "goto", "if", "import", "interface",
    "map", "nil", "package", "range", "return", "select", "struct", "switch",
    "type", "var",
  ]),
  java: new Set([
    "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char",
    "class", "const", "continue", "default", "do", "double", "else", "enum",
    "exports", "extends", "final", "finally", "float", "for", "if", "implements",
    "import", "instanceof", "int", "interface", "long", "module", "native",
    "new", "non-sealed", "null", "opens", "package", "permits", "private",
    "protected", "public", "record", "requires", "return", "sealed", "short",
    "static", "strictfp", "super", "switch", "synchronized", "this", "throw",
    "throws", "transient", "transitive", "try", "uses", "var", "void",
    "volatile", "while", "with", "yield",
  ]),
  ruby: new Set([
    "alias", "and", "begin", "break", "case", "class", "def", "defined?",
    "do", "else", "elsif", "end", "ensure", "false", "for", "if", "in",
    "module", "next", "nil", "not", "or", "redo", "rescue", "retry", "return",
    "self", "super", "then", "true", "undef", "unless", "until", "when",
    "while", "yield", "false", "nil",
  ]),
  csharp: new Set([
    "abstract", "as", "async", "await", "base", "bool", "break", "byte", "case",
    "catch", "char", "checked", "class", "const", "continue", "decimal",
    "default", "delegate", "do", "double", "else", "enum", "event", "explicit",
    "extern", "false", "finally", "fixed", "float", "for", "foreach", "from",
    "get", "global", "goto", "if", "implicit", "in", "init", "int", "interface",
    "internal", "is", "lock", "long", "namespace", "new", "null", "object",
    "operator", "out", "override", "params", "partial", "private", "protected",
    "public", "readonly", "record", "ref", "required", "return", "sbyte",
    "sealed", "set", "short", "sizeof", "stackalloc", "static", "string",
    "struct", "switch", "this", "throw", "true", "try", "typeof", "uint",
    "ulong", "unchecked", "unsafe", "ushort", "using", "var", "virtual", "void",
    "volatile", "when", "where", "while", "yield",
  ]),
  cpp: new Set([
    "alignas", "alignof", "and", "asm", "auto", "bitand", "bitor", "bool",
    "break", "case", "catch", "char", "class", "concept", "const", "consteval",
    "constexpr", "constinit", "const_cast", "continue", "co_await", "co_return",
    "co_yield", "decltype", "default", "delete", "do", "double", "dynamic_cast",
    "else", "enum", "explicit", "export", "extern", "false", "float", "for",
    "friend", "goto", "if", "inline", "int", "long", "mutable", "namespace",
    "new", "noexcept", "nullptr", "operator", "or", "private", "protected",
    "public", "register", "reinterpret_cast", "requires", "return", "short",
    "signed", "sizeof", "static", "static_assert", "static_cast", "struct",
    "switch", "template", "this", "thread_local", "throw", "true", "try",
    "typedef", "typeid", "typename", "union", "unsigned", "using", "virtual",
    "void", "volatile", "wchar_t", "while",
  ]),
  c: new Set([
    "auto", "break", "case", "char", "const", "continue", "default", "do",
    "double", "else", "enum", "extern", "float", "for", "goto", "if", "inline",
    "int", "long", "register", "restrict", "return", "short", "signed",
    "sizeof", "static", "struct", "switch", "typedef", "union", "unsigned",
    "void", "volatile", "while", "_Alignas", "_Alignof", "_Atomic", "_Bool",
    "_Complex", "_Generic", "_Imaginary", "_Noreturn", "_Static_assert",
    "_Thread_local",
  ]),
});

const TYPES = new Set([
  "any", "Array", "bool", "boolean", "byte", "char", "decimal", "dict",
  "double", "f32", "f64", "float", "HashMap", "i8", "i16", "i32", "i64",
  "int", "integer", "List", "long", "Map", "never", "number", "object",
  "Option", "Result", "Set", "short", "size_t", "str", "string", "String",
  "tuple", "u8", "u16", "u32", "u64", "uint", "ulong", "unknown", "usize",
  "Vec", "void",
]);
const BUILTINS = new Set([
  "console", "document", "enumerate", "Error", "Exception", "fetch", "len",
  "Math", "Object", "print", "Promise", "range", "require", "self", "std",
  "super", "System", "window",
]);
const MAX_SYNTAX_CHARACTERS = 20_000;

/** Language identity is path-derived, so one diff can safely contain many languages. */
export function syntaxLanguageForPath(path: string): string {
  return languageForCodeExtension(extname(path)) ?? "plain";
}

function quoteEnd(text: string, start: number, quote: string): number {
  let cursor = start + quote.length;
  while (cursor < text.length) {
    if (text[cursor] === "\\") cursor += 2;
    else if (text.startsWith(quote, cursor)) return cursor + quote.length;
    else cursor += 1;
  }
  return text.length;
}

function push(
  spans: SyntaxSpan[],
  start: number,
  end: number,
  style: SyntaxStyle,
): void {
  if (end > start) spans.push({ start, end, style });
}

function htmlSpans(text: string): SyntaxSpan[] {
  const spans: SyntaxSpan[] = [];
  for (const comment of text.matchAll(/<!--[\s\S]*?(?:-->|$)/gu)) {
    push(spans, comment.index, comment.index + comment[0].length, "comment");
  }
  for (const tag of text.matchAll(/<\/?([A-Za-z][\w:-]*)\b[^>]*>?/gu)) {
    const start = tag.index;
    const tagName = tag[1]!;
    const nameOffset = tag[0].indexOf(tagName);
    push(spans, start + nameOffset, start + nameOffset + tagName.length, "tag");
    for (const attribute of tag[0].matchAll(/\b([A-Za-z_:][\w:.-]*)(?=\s*=)/gu)) {
      push(
        spans,
        start + attribute.index,
        start + attribute.index + attribute[1]!.length,
        "property",
      );
    }
    for (const string of tag[0].matchAll(/(["'])[\s\S]*?\1/gu)) {
      push(
        spans,
        start + string.index,
        start + string.index + string[0].length,
        "string",
      );
    }
  }
  return spans.sort((left, right) => left.start - right.start || right.end - left.end);
}

function cssSpans(text: string): SyntaxSpan[] {
  const spans: SyntaxSpan[] = [];
  for (const comment of text.matchAll(/\/\*[\s\S]*?(?:\*\/|$)/gu)) {
    push(spans, comment.index, comment.index + comment[0].length, "comment");
  }
  for (const atRule of text.matchAll(/@[A-Za-z-]+/gu)) {
    push(spans, atRule.index, atRule.index + atRule[0].length, "decorator");
  }
  for (const property of text.matchAll(/(?:^|[;{]\s*)(--?[A-Za-z_][\w-]*|[A-Za-z][\w-]*)(?=\s*:)/gu)) {
    const name = property[1]!;
    const offset = property[0].lastIndexOf(name);
    push(spans, property.index + offset, property.index + offset + name.length, "property");
  }
  for (const string of text.matchAll(/(["'])[\s\S]*?\1/gu)) {
    push(spans, string.index, string.index + string[0].length, "string");
  }
  for (const number of text.matchAll(/\b\d+(?:\.\d+)?(?:%|[A-Za-z]+)?\b/gu)) {
    push(spans, number.index, number.index + number[0].length, "number");
  }
  return spans.sort((left, right) => left.start - right.start || right.end - left.end);
}

/** Tokenize one display line using the grammar family selected by its path. */
export function syntaxSpansForLine(path: string, text: string): SyntaxSpan[] {
  const language = syntaxLanguageForPath(path);
  // Generated bytes stay intact; only presentation work is capped for hostile
  // or minified single-line files.
  const lexicalText = text.slice(0, MAX_SYNTAX_CHARACTERS);
  if (language === "html") return htmlSpans(lexicalText);
  if (language === "css") return cssSpans(lexicalText);
  if (language === "plain") return [];

  const spans: SyntaxSpan[] = [];
  const hashComments = language === "python" || language === "ruby";
  const cComments = !hashComments;
  let cursor = 0;
  while (cursor < lexicalText.length) {
    if (hashComments && lexicalText[cursor] === "#") {
      push(spans, cursor, lexicalText.length, "comment");
      break;
    }
    if (cComments && lexicalText.startsWith("//", cursor)) {
      push(spans, cursor, lexicalText.length, "comment");
      break;
    }
    if (cComments && lexicalText.startsWith("/*", cursor)) {
      const end = lexicalText.indexOf("*/", cursor + 2);
      push(spans, cursor, end < 0 ? lexicalText.length : end + 2, "comment");
      cursor = end < 0 ? lexicalText.length : end + 2;
      continue;
    }
    if (
      (language === "c" || language === "cpp")
      && lexicalText[cursor] === "#"
      && lexicalText.slice(0, cursor).trim().length === 0
    ) {
      push(spans, cursor, lexicalText.length, "decorator");
      break;
    }
    if (
      (language === "python" || language === "ruby")
      && lexicalText[cursor] === "@"
      && /[A-Za-z_]/u.test(lexicalText[cursor + 1] ?? "")
    ) {
      const match = /^@[A-Za-z_]\w*/u.exec(lexicalText.slice(cursor))!;
      push(spans, cursor, cursor + match[0].length, "decorator");
      cursor += match[0].length;
      continue;
    }
    const quote =
      lexicalText.startsWith('"""', cursor) || lexicalText.startsWith("'''", cursor)
        ? lexicalText.slice(cursor, cursor + 3)
        : ["'", '"', "`"].includes(lexicalText[cursor] ?? "")
          ? lexicalText[cursor]!
          : undefined;
    if (quote !== undefined) {
      const end = quoteEnd(lexicalText, cursor, quote);
      push(spans, cursor, end, "string");
      cursor = end;
      continue;
    }
    const number = /^(?:0[xob][\da-f]+|\d+(?:\.\d+)?(?:e[+-]?\d+)?)[A-Za-z_]*/iu
      .exec(lexicalText.slice(cursor));
    if (number !== null) {
      push(spans, cursor, cursor + number[0].length, "number");
      cursor += number[0].length;
      continue;
    }
    const identifier = /^[A-Za-z_$][\w$]*/u.exec(lexicalText.slice(cursor));
    if (identifier !== null) {
      const value = identifier[0];
      const end = cursor + value.length;
      const rest = lexicalText.slice(end);
      const keywords = KEYWORDS[language] ?? new Set<string>();
      const style: SyntaxStyle | undefined =
        keywords.has(value)
          ? "keyword"
          : TYPES.has(value) || /^[A-Z][A-Za-z0-9_]*$/u.test(value)
            ? "type"
            : BUILTINS.has(value)
              ? "builtin"
              : /^\s*\(/u.test(rest)
                ? "function"
                : undefined;
      if (style !== undefined) push(spans, cursor, end, style);
      cursor = end;
      continue;
    }
    cursor += 1;
  }
  return spans;
}
